Week 2: implementation for remaining functions, grade 8/10 so passed with that but a few tests still fail with
[Test Description] correct solution for level 6 (5pts)(streams.BloxorzSuite)
[Observed Error] class java.lang.IllegalArgumentException: requirement failed
java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:327)
	at streams.BloxorzSuite$SolutionChecker.$anonfun$solve$1(BloxorzSuite.scala:17)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:170)
	at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:166)
	at scala.collection.immutable.List.foldLeft(List.scala:82)
	at streams.BloxorzSuite$SolutionChecker.solve(BloxorzSuite.scala:16)